### ISSUE TITLE
Incorrect UI initialization

### ISSUE THREAD

**Issue by tuxcy17** [IdoO2/pyparse#16]
when executing view.py with basics data, UI & computer are running very slowly.

Log :
```
(python3:23381): Gtk-CRITICAL **: IA__gtk_widget_style_get: assertion 'GTK_IS_WIDGET (widget)' failed
(python3:23381): Gtk-CRITICAL **: IA__gtk_widget_style_get: assertion 'GTK_IS_WIDGET (widget)' failed
QXcbShmImage: shmget() failed (22) for size 1073610756 (16383x16383)
```

**Comment by IdoO2** [comment]
À tout hasard essaye de commenter la ligne 87 de `view.py` (`self.setCentralWidget(self.__tree)`).

**Comment by tuxcy17** [comment]
Après de nombreux tests il semble que le problème soit dans buildMenu.
Avec ce code j'arrive à avoir l'interface
```
    def __buildWindow(self):
        """ Create window

            Sets default window title,
            adds menu bar items,
            actually lays out the window,
            stores the model for further update
        """
        # self.__buildMenu()
        self.content = QVBoxLayout()
        self.content.addWidget(self.__tree)
        self.setGeometry(300, 300, 300, 150)
        self.setWindowTitle()
        self.setCentralWidget(self.__tree)
```

**Comment by tuxcy17** [comment]
Il doit y avoir un bug au niveau du layout. 
En gros soit : 
     - je peux afficher la menu bar et dans ce cas l'arbre n'apparait pas (je commente setCentralWidget)
     - je peux afficher l'arbre mais pas la menu bar (je commente buildMenu)

**Comment by tuxcy17** [comment]
J'ai trouvé la cause du bug sans que celle-ci soit précise. 
Celui-ci provient de la config de Qt/PyQT et sans doute de la version de la librairie tierce (libglu1-mesa-dev) utilisé pour compiler PyQT.

Je donne ma config comme exemple : 
Qt 5.5.0
Python 3.4.3
PyQt 5.5
libglu1-mesa-dev 8.0.4
